version: "3.8"

services:
  # MySQL service
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - db

  web:
    image: php:8.2-apache
    container_name: web
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - db
    command: bash -c "chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html && apache2-foreground"

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
